server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    max-keep-alive-requests: 15
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo

logging:
  pattern:
    level: "%5p [${spring.application.name}]"
  level:
    root: info
    org.catalog: debug

